name: Packaging

on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setenv
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - uses: purcell/setup-emacs@master
        with:
          version: 28.1

      - uses: conao3/setup-cask@master
        with:
          version: 0.8.9

      - name: install
        run: "cask install"

      - name: build
        run: "cask build"

      - name: package
        run: "cask package"
